version: "3.5"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./postgresgb-data:/var/lib/postgresql/data
  app:
    container_name: app
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - postgres
volumes:
  postgresgb-data:

